"""Lay out the phone apps' Briefcase project under build/mobile/.

    python mobile/stage.py [--version 1.7.2] [--android] [--ios]

Briefcase takes an app's sources from beside its pyproject.toml, and the app
is the repo's own app/, not a copy kept in mobile/. So this copies in what the
phone app is made of, then fills in what Briefcase cannot get by itself:

  * the app (app/), its templates (resources/) and the built panel
    (webui/dist, which `npm run build` makes first), beside the shell
    (mobile/src/llmselfbot)
  * the version, from the release tag: into pyproject.toml, which becomes the
    APK's versionName and code and the IPA's version, and into app/_build.py,
    which the app itself reports (app/version.py)
  * wheels/: the stand-ins for jiter and audioop-lts (mobile/shims); with
    --android, curl_cffi's own Android build asking for the cffi Android has
    (see relaxed_curl_cffi) and discord_protos as a wheel; with --ios, PyYAML as plain Python (it publishes
    no iOS build, and Briefcase installs only built wheels for iOS)
  * icons/: every size Android and iOS ask for, made from resources/icon.png

Then, from build/mobile/: briefcase create android, and so on (see the
android and ios jobs in .github/workflows/build-exe.yml).
"""

import argparse
import re
import shutil
import subprocess
import sys
import tarfile
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MOBILE = ROOT / "mobile"
OUT = ROOT / "build" / "mobile"

# What Briefcase's templates ask for (their briefcase.toml): Android's round,
# square and adaptive launcher icons and its splash; iOS's app icons and splash.
ANDROID = {"round": (48, 72, 96, 144, 192), "square": (48, 72, 96, 144, 192, 320, 480, 640, 960, 1280),
           "adaptive": (108, 162, 216, 324, 432)}
IOS = (20, 29, 40, 58, 60, 76, 80, 87, 120, 152, 167, 180, 640, 1024, 1280, 1920)
BACKGROUND = (13, 11, 20, 255)          # the panel's own dark


def copy_tree(src: Path, dest: Path):
    skip = shutil.ignore_patterns("__pycache__", "*.pyc", "node_modules", ".pytest_cache")
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(src, dest, ignore=skip)


def stage_sources(version: str):
    src = OUT / "src"
    src.mkdir(parents=True, exist_ok=True)
    copy_tree(MOBILE / "src" / "llmselfbot", src / "llmselfbot")
    copy_tree(ROOT / "app", src / "app")
    copy_tree(ROOT / "resources", src / "resources")
    dist = ROOT / "webui" / "dist"
    if not (dist / "index.html").exists():
        sys.exit("webui/dist is missing: run `npm run build` in webui first")
    copy_tree(dist, src / "webui" / "dist")
    # The version the app reports, as the desktop builds stamp it.
    (src / "app" / "_build.py").write_text(
        "# Generated by mobile/stage.py for the phone apps.\n"
        f'VERSION = "{version}"\n', encoding="utf-8")
    shutil.copy(ROOT / "LICENSE", OUT / "LICENSE")

    text = (MOBILE / "pyproject.toml").read_text(encoding="utf-8")
    # Briefcase wants a plain version ("1.7.2-beta" becomes 1.7.2), and turns
    # it into Android's version code, which 0.0.0 leaves empty: a build that
    # is not a release is 0.0.1 there (the app itself still says 0.0.0-dev).
    plain = re.match(r"\d+(\.\d+){0,2}", version)
    packaged = plain.group(0) if plain else "0.0.1"
    if not any(int(n) for n in packaged.split(".")):
        packaged = "0.0.1"
    text = re.sub(r'(?m)^version = "[^"]*"', f'version = "{packaged}"', text, count=1)
    (OUT / "pyproject.toml").write_text(text, encoding="utf-8")


def build_wheels(android: bool, ios: bool):
    wheels = OUT / "wheels"
    if wheels.exists():
        shutil.rmtree(wheels)
    wheels.mkdir(parents=True)
    for shim in ("jiter", "audioop-lts"):
        subprocess.run([sys.executable, "-m", "pip", "wheel", "--no-deps", "-w", str(wheels),
                        str(MOBILE / "shims" / shim)], check=True)
    if android:
        relaxed_curl_cffi(wheels)
        # discord.py-self wants discord_protos below 1.0, published only as
        # source: plain Python, built into a wheel here rather than left for
        # the phone build to build.
        subprocess.run([sys.executable, "-m", "pip", "wheel", "--no-deps", "-w", str(wheels),
                        "discord-protos==0.0.2"], check=True)
    if ios:
        pure_pyyaml(wheels)


def _pypi_file(name: str, version: str, pick) -> tuple[bytes, str]:
    """One file of a PyPI release, checked against PyPI's own checksum."""
    import hashlib
    import json
    import urllib.request
    with urllib.request.urlopen(f"https://pypi.org/pypi/{name}/{version}/json", timeout=60) as r:
        meta = json.loads(r.read())
    entry = next(u for u in meta["urls"] if pick(u))
    with urllib.request.urlopen(entry["url"], timeout=180) as r:
        data = r.read()
    if hashlib.sha256(data).hexdigest() != entry["digests"]["sha256"]:
        sys.exit(f"{entry['filename']} did not match PyPI's checksum")
    return data, entry["filename"]


def relaxed_curl_cffi(wheels: Path, version: str = "0.16.3"):
    """curl_cffi's official Android wheel, asking for the cffi Android has.

    Discord's library sends everything through curl_cffi, and curl_cffi's
    releases with an Android build (0.15 and later) say they need cffi 2.0,
    which nobody builds for Android: Chaquopy's index, where Android's cffi
    comes from, has 1.17.1. Only the requirement is in the way. The compiled
    part announces itself to cffi's runtime with the oldest module version
    (0x2601: it uses none of the types that raised it), which 1.17.1 accepts
    as readily as 2.0 does. So the wheel is taken as published, with only that
    line of its metadata relaxed, and renumbered 0.16.3+phone so pip prefers
    it over the untouched one. Nothing compiled is changed.
    """
    import base64
    import hashlib
    import io
    import zipfile
    data, filename = _pypi_file("curl-cffi", version,
                                lambda u: u["filename"].endswith("-cp313-cp313-android_24_arm64_v8a.whl"))
    local = f"{version}+phone"
    old_info = f"curl_cffi-{version}.dist-info/"
    new_info = f"curl_cffi-{local}.dist-info/"
    src = zipfile.ZipFile(io.BytesIO(data))
    files = {}
    for item in src.infolist():
        body = src.read(item.filename)
        name = item.filename.replace(old_info, new_info, 1)
        if name == new_info + "METADATA":
            text = body.decode("utf-8")
            text = text.replace(f"Version: {version}\n", f"Version: {local}\n", 1)
            relaxed = re.sub(r"(?m)^Requires-Dist: cffi\s*>=\s*2[^\n;]*", "Requires-Dist: cffi>=1.12.0", text)
            if relaxed == text:
                sys.exit("curl_cffi no longer asks for cffi 2: look again before relaxing anything")
            body = relaxed.encode("utf-8")
        files[name] = body
    record_name = new_info + "RECORD"
    lines = []
    for name, body in files.items():
        if name == record_name:
            continue
        digest = base64.urlsafe_b64encode(hashlib.sha256(body).digest()).rstrip(b"=").decode()
        lines.append(f"{name},sha256={digest},{len(body)}")
    lines.append(f"{record_name},,")
    files[record_name] = ("\n".join(lines) + "\n").encode("utf-8")
    out = wheels / filename.replace(f"curl_cffi-{version}-", f"curl_cffi-{local}-", 1)
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
        for name, body in files.items():
            z.writestr(name, body)
    print(f"relaxed {filename} -> {out.name}")


def pure_pyyaml(wheels: Path, version: str = "6.0.3"):
    """PyYAML without its C half: its own pure-Python package, in a wheel."""
    import hashlib
    import json
    import urllib.request
    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp)
        # Straight from PyPI: `pip download` of a source release builds its
        # metadata first, which for PyYAML means its C half.
        with urllib.request.urlopen(f"https://pypi.org/pypi/PyYAML/{version}/json", timeout=60) as r:
            meta = json.loads(r.read())
        release = next(u for u in meta["urls"] if u["packagetype"] == "sdist")
        sdist = tmp / release["filename"]
        with urllib.request.urlopen(release["url"], timeout=120) as r:
            sdist.write_bytes(r.read())
        if hashlib.sha256(sdist.read_bytes()).hexdigest() != release["digests"]["sha256"]:
            sys.exit("PyYAML's source did not match PyPI's checksum")
        with tarfile.open(sdist) as tar:
            tar.extractall(tmp / "src", filter="data")
        lib = next((tmp / "src").glob("*/lib/yaml"))
        project = tmp / "pyyaml-pure"
        shutil.copytree(lib, project / "yaml")
        (project / "pyproject.toml").write_text(
            '[build-system]\nrequires = ["setuptools>=61"]\nbuild-backend = "setuptools.build_meta"\n\n'
            f'[project]\nname = "PyYAML"\nversion = "{version}"\nrequires-python = ">=3.8"\n\n'
            '[tool.setuptools]\npackages = ["yaml"]\n', encoding="utf-8")
        subprocess.run([sys.executable, "-m", "pip", "wheel", "--no-deps", "-w", str(wheels), str(project)],
                       check=True)


def make_icons():
    from PIL import Image, ImageDraw
    art = Image.open(ROOT / "resources" / "icon.png").convert("RGBA")
    icons = OUT / "icons"
    icons.mkdir(parents=True, exist_ok=True)

    def on_ground(size: int, share: float, shape: str = "square") -> Image.Image:
        """The icon at `share` of a `size` tile of the panel's dark."""
        tile = Image.new("RGBA", (size, size), BACKGROUND)
        inner = max(1, round(size * share))
        piece = art.resize((inner, inner), Image.LANCZOS)
        tile.alpha_composite(piece, ((size - inner) // 2, (size - inner) // 2))
        if shape == "round":
            mask = Image.new("L", (size, size), 0)
            ImageDraw.Draw(mask).ellipse((0, 0, size - 1, size - 1), fill=255)
            tile.putalpha(mask)
        return tile

    for variant, sizes in ANDROID.items():
        for size in sizes:
            if variant == "adaptive":
                # The foreground layer: the art inside the middle two thirds,
                # on nothing; Android draws the background and the mask.
                tile = Image.new("RGBA", (size, size), (0, 0, 0, 0))
                inner = round(size * 0.6)
                tile.alpha_composite(art.resize((inner, inner), Image.LANCZOS),
                                     ((size - inner) // 2, (size - inner) // 2))
            elif size >= 320:
                tile = on_ground(size, 0.3)                  # the splash: the icon small in the middle
            else:
                tile = on_ground(size, 0.86, "round" if variant == "round" else "square")
            tile.save(icons / f"llmselfbot-{variant}-{size}.png")
    for size in IOS:
        # iOS icons may not be see-through; the splash is the icon in the middle.
        tile = on_ground(size, 0.3 if size in (640, 1280, 1920) else 0.86)
        tile.convert("RGB").save(icons / f"llmselfbot-{size}.png")


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--version", default="0.0.0", help="the release, as the tag says it (v1.7.2 or 1.7.2)")
    ap.add_argument("--android", action="store_true", help="also make the wheels only the Android app needs")
    ap.add_argument("--ios", action="store_true", help="also make the wheels only the iPhone app needs")
    args = ap.parse_args()
    version = args.version.lstrip("vV") or "0.0.0"
    OUT.mkdir(parents=True, exist_ok=True)
    stage_sources(version)
    build_wheels(args.android, args.ios)
    make_icons()
    print(f"staged {version} in {OUT}")


if __name__ == "__main__":
    main()
