/**
 * The emoji the picker offers, grouped so they can be browsed.
 *
 * Generated from the `emoji` package's Unicode data rather than typed out:
 * 1908 entries is not something to maintain by hand, and a wrong codepoint
 * renders as a box rather than failing visibly. Only fully-qualified
 * sequences are included, and skin-tone and hair variants are left out -
 * they multiply the list several times over without offering a different
 * choice, and the bot reacts with a plain emoji anyway.
 *
 * Each entry is [character, searchable name]. Categories are derived from
 * the names, except flags, which are regional-indicator pairs whose names
 * are the country and so have to be found by codepoint.
 */

export type EmojiEntry = [string, string];

export const EMOJI_GROUPS: { name: string; items: EmojiEntry[] }[] = [
  {
    name: "Smileys",
    items: [
      ["👽","alien"],["👾","alien monster"],["😠","angry face"],["👿","angry face with horns"],["😧","anguished face"],["😰","anxious face with sweat"],
      ["😲","astonished face"],["😁","beaming face with smiling eyes"],["🧃","beverage box"],["🥣","bowl with spoon"],["🐱","cat face"],["😹","cat with tears of joy"],
      ["😼","cat with wry smile"],["🤡","clown face"],["🥶","cold face"],["😖","confounded face"],["😕","confused face"],["🐮","cow face"],
      ["🤠","cowboy hat face"],["🫫","cracking face"],["😿","crying cat"],["😢","crying face"],["🔮","crystal ball"],["😞","disappointed face"],
      ["🥸","disguised face"],["🫪","distorted face"],["🐶","dog face"],["🫥","dotted line face"],["😓","downcast face with sweat"],["🐲","dragon face"],
      ["🤤","drooling face"],["😡","enraged face"],["😑","expressionless face"],["😘","face blowing a kiss"],["😮‍💨","face exhaling"],["🥹","face holding back tears"],
      ["😶‍🌫️","face in clouds"],["😋","face savoring food"],["😱","face screaming in fear"],["🤮","face vomiting"],["🫩","face with bags under eyes"],["😵","face with crossed-out eyes"],
      ["🫤","face with diagonal mouth"],["🤭","face with hand over mouth"],["🤕","face with head-bandage"],["😷","face with medical mask"],["🧐","face with monocle"],["🫢","face with open eyes and hand over mouth"],
      ["😮","face with open mouth"],["🫣","face with peeking eye"],["🤨","face with raised eyebrow"],["🙄","face with rolling eyes"],["😵‍💫","face with spiral eyes"],["😤","face with steam from nose"],
      ["🤬","face with symbols on mouth"],["😂","face with tears of joy"],["🤒","face with thermometer"],["😛","face with tongue"],["😶","face without mouth"],["😨","fearful face"],
      ["🌛","first quarter moon face"],["😳","flushed face"],["🍤","fried shrimp"],["☹️","frowning face"],["😦","frowning face with open mouth"],["🌝","full moon face"],
      ["👻","ghost"],["👺","goblin"],["😬","grimacing face"],["😺","grinning cat"],["😸","grinning cat with smiling eyes"],["😀","grinning face"],
      ["😃","grinning face with big eyes"],["😄","grinning face with smiling eyes"],["😅","grinning face with sweat"],["😆","grinning squinting face"],["🙉","hear-no-evil monkey"],["🐴","horse face"],
      ["☕","hot beverage"],["🥵","hot face"],["😯","hushed face"],["💏","kiss"],["👨‍❤️‍💋‍👨","kiss man man"],["💋","kiss mark"],
      ["👩‍❤️‍💋‍👨","kiss woman man"],["👩‍❤️‍💋‍👩","kiss woman woman"],["😽","kissing cat"],["😗","kissing face"],["😚","kissing face with closed eyes"],["😙","kissing face with smiling eyes"],
      ["🌜","last quarter moon face"],["😭","loudly crying face"],["🤥","lying face"],["🤦‍♂️","man facepalming"],["🫠","melting face"],["🤑","money-mouth face"],
      ["🐒","monkey"],["🐵","monkey face"],["🐭","mouse face"],["🤢","nauseated face"],["🤓","nerd face"],["😐","neutral face"],
      ["🌚","new moon face"],["👹","ogre"],["🥳","partying face"],["😔","pensive face"],["🫂","people hugging"],["😣","persevering face"],
      ["🤦","person facepalming"],["👲","person with skullcap"],["🐷","pig face"],["💩","pile of poo"],["🥺","pleading face"],["🐩","poodle"],
      ["🎱","pool 8 ball"],["🐰","rabbit face"],["😌","relieved face"],["🤖","robot"],["🤣","rolling on the floor laughing"],["😥","sad but relieved face"],
      ["🫡","saluting face"],["🙈","see-no-evil monkey"],["🫨","shaking face"],["🦐","shrimp"],["🤫","shushing face"],["💀","skull"],
      ["☠️","skull and crossbones"],["😴","sleeping face"],["😪","sleepy face"],["🙁","slightly frowning face"],["🙂","slightly smiling face"],["😻","smiling cat with heart-eyes"],
      ["☺️","smiling face"],["😇","smiling face with halo"],["😍","smiling face with heart-eyes"],["🥰","smiling face with hearts"],["😈","smiling face with horns"],["🤗","smiling face with open hands"],
      ["😊","smiling face with smiling eyes"],["😎","smiling face with sunglasses"],["🥲","smiling face with tear"],["😏","smirking face"],["🤧","sneezing face"],["🙊","speak-no-evil monkey"],
      ["🥄","spoon"],["😝","squinting face with tongue"],["🌞","sun with face"],["📆","tear-off calendar"],["🤔","thinking face"],["🐯","tiger face"],
      ["😫","tired face"],["😒","unamused face"],["🙃","upside-down face"],["😩","weary face"],["🌬️","wind face"],["😉","winking face"],
      ["😜","winking face with tongue"],["🤦‍♀️","woman facepalming"],["🥴","woozy face"],["😟","worried face"],["🥱","yawning face"],["🤪","zany face"],
      ["🤐","zipper-mouth face"],
    ],
  },
  {
    name: "People",
    items: [
      ["👌","OK hand"],["🎅","Santa Claus"],["⏰","alarm clock"],["🏈","american football"],["🫀","anatomical heart"],["🧑‍🎨","artist"],
      ["🎨","artist palette"],["🧑‍🚀","astronaut"],["👶","baby"],["👼","baby angel"],["🍼","baby bottle"],["🐤","baby chick"],
      ["🚼","baby symbol"],["👇","backhand index pointing down"],["👈","backhand index pointing left"],["👉","backhand index pointing right"],["👆","backhand index pointing up"],["🧑‍🩰","ballet dancer"],
      ["🛁","bathtub"],["🐻","bear"],["💓","beating heart"],["🖤","black heart"],["💙","blue heart"],["🦴","bone"],
      ["👦","boy"],["🧠","brain"],["🤱","breast-feeding"],["💔","broken heart"],["🤎","brown heart"],["🎯","bullseye"],
      ["🤙","call me hand"],["🧒","child"],["🚸","children crossing"],["🎬","clapper board"],["👏","clapping hands"],["👷","construction worker"],
      ["🧑‍🍳","cook"],["🍚","cooked rice"],["🍪","cookie"],["🍳","cooking"],["💑","couple with heart"],["👨‍❤️‍👨","couple with heart man man"],
      ["👩‍❤️‍👨","couple with heart woman man"],["👩‍❤️‍👩","couple with heart woman woman"],["🤞","crossed fingers"],["🧏‍♂️","deaf man"],["🧏","deaf person"],["🧏‍♀️","deaf woman"],
      ["🕵️","detective"],["👂","ear"],["🌽","ear of corn"],["🦻","ear with hearing aid"],["🧝","elf"],["👁️","eye"],
      ["👁️‍🗨️","eye in speech bubble"],["👀","eyes"],["🧑‍🏭","factory worker"],["🧚","fairy"],["👪","family"],["🧑‍🧑‍🧒","family adult adult child"],
      ["🧑‍🧑‍🧒‍🧒","family adult adult child child"],["🧑‍🧒","family adult child"],["🧑‍🧒‍🧒","family adult child child"],["👨‍👦","family man boy"],["👨‍👦‍👦","family man boy boy"],["👨‍👧","family man girl"],
      ["👨‍👧‍👦","family man girl boy"],["👨‍👧‍👧","family man girl girl"],["👨‍👨‍👦","family man man boy"],["👨‍👨‍👦‍👦","family man man boy boy"],["👨‍👨‍👧","family man man girl"],["👨‍👨‍👧‍👦","family man man girl boy"],
      ["👨‍👨‍👧‍👧","family man man girl girl"],["👨‍👩‍👦","family man woman boy"],["👨‍👩‍👦‍👦","family man woman boy boy"],["👨‍👩‍👧","family man woman girl"],["👨‍👩‍👧‍👦","family man woman girl boy"],["👨‍👩‍👧‍👧","family man woman girl girl"],
      ["👩‍👦","family woman boy"],["👩‍👦‍👦","family woman boy boy"],["👩‍👧","family woman girl"],["👩‍👧‍👦","family woman girl boy"],["👩‍👧‍👧","family woman girl girl"],["👩‍👩‍👦","family woman woman boy"],
      ["👩‍👩‍👦‍👦","family woman woman boy boy"],["👩‍👩‍👧","family woman woman girl"],["👩‍👩‍👧‍👦","family woman woman girl boy"],["👩‍👩‍👧‍👧","family woman woman girl girl"],["🧑‍🌾","farmer"],["📁","file folder"],
      ["🫆","fingerprint"],["🧑‍🚒","firefighter"],["🙏","folded hands"],["🪭","folding hand fan"],["🦶","foot"],["👣","footprints"],
      ["🥠","fortune cookie"],["🐥","front-facing baby chick"],["⚙️","gear"],["🧞","genie"],["👧","girl"],["💚","green heart"],
      ["🩶","grey heart"],["💗","growing heart"],["💂","guard"],["🖐️","hand with fingers splayed"],["🫰","hand with index finger and thumb crossed"],["👜","handbag"],
      ["🤝","handshake"],["🧑‍⚕️","health worker"],["💟","heart decoration"],["❣️","heart exclamation"],["🫶","heart hands"],["❤️‍🔥","heart on fire"],
      ["♥️","heart suit"],["💘","heart with arrow"],["💝","heart with ribbon"],["🧑‍⚖️","judge"],["🪯","khanda"],["🤛","left-facing fist"],
      ["🫲","leftwards hand"],["🫷","leftwards pushing hand"],["🫹","leftwards thumb sign"],["🦵","leg"],["🩵","light blue heart"],["🫁","lungs"],
      ["🧙","mage"],["👨","man"],["👨‍🎨","man artist"],["👨‍🚀","man astronaut"],["👨‍🦲","man bald"],["🧔‍♂️","man beard"],
      ["🚴‍♂️","man biking"],["⛹️‍♂️","man bouncing ball"],["🙇‍♂️","man bowing"],["🤸‍♂️","man cartwheeling"],["🧗‍♂️","man climbing"],["👷‍♂️","man construction worker"],
      ["👨‍🍳","man cook"],["🕺","man dancing"],["🕵️‍♂️","man detective"],["🧝‍♂️","man elf"],["👨‍🏭","man factory worker"],["🧚‍♂️","man fairy"],
      ["👨‍🌾","man farmer"],["👨‍🍼","man feeding baby"],["👨‍🚒","man firefighter"],["🙍‍♂️","man frowning"],["🧞‍♂️","man genie"],["🙅‍♂️","man gesturing NO"],
      ["🙆‍♂️","man gesturing OK"],["💆‍♂️","man getting massage"],["🏌️‍♂️","man golfing"],["💂‍♂️","man guard"],["👨‍⚕️","man health worker"],["🧘‍♂️","man in lotus position"],
      ["👨‍🦽","man in manual wheelchair"],["👨‍🦽‍➡️","man in manual wheelchair facing right"],["👨‍🦼","man in motorized wheelchair"],["👨‍🦼‍➡️","man in motorized wheelchair facing right"],["🧖‍♂️","man in steamy room"],["🤵‍♂️","man in tuxedo"],
      ["👨‍⚖️","man judge"],["🤹‍♂️","man juggling"],["🧎‍♂️","man kneeling"],["🧎‍♂️‍➡️","man kneeling facing right"],["🏋️‍♂️","man lifting weights"],["🧙‍♂️","man mage"],
      ["👨‍🔧","man mechanic"],["🚵‍♂️","man mountain biking"],["👨‍💼","man office worker"],["👨‍✈️","man pilot"],["🤾‍♂️","man playing handball"],["🤽‍♂️","man playing water polo"],
      ["👮‍♂️","man police officer"],["🙎‍♂️","man pouting"],["🙋‍♂️","man raising hand"],["🚣‍♂️","man rowing boat"],["🏃‍♂️","man running"],["🏃‍♂️‍➡️","man running facing right"],
      ["👨‍🔬","man scientist"],["🤷‍♂️","man shrugging"],["👨‍🎤","man singer"],["🧍‍♂️","man standing"],["👨‍🎓","man student"],["🦸‍♂️","man superhero"],
      ["🦹‍♂️","man supervillain"],["🏄‍♂️","man surfing"],["🏊‍♂️","man swimming"],["👨‍🏫","man teacher"],["👨‍💻","man technologist"],["💁‍♂️","man tipping hand"],
      ["🧛‍♂️","man vampire"],["🚶‍♂️","man walking"],["🚶‍♂️‍➡️","man walking facing right"],["👳‍♂️","man wearing turban"],["👰‍♂️","man with veil"],["👨‍🦯","man with white cane"],
      ["👨‍🦯‍➡️","man with white cane facing right"],["🧟‍♂️","man zombie"],["🥭","mango"],["🕰️","mantelpiece clock"],["🦽","manual wheelchair"],["👞","man\u2019s shoe"],
      ["🍖","meat on bone"],["🧑‍🔧","mechanic"],["🦾","mechanical arm"],["🦿","mechanical leg"],["👬","men holding hands"],["👯‍♂️","men with bunny ears"],
      ["🤼‍♂️","men wrestling"],["❤️‍🩹","mending heart"],["🧜‍♂️","merman"],["🧜","merperson"],["🖕","middle finger"],["👄","mouth"],
      ["💅","nail polish"],["🪍","net with handle"],["👃","nose"],["🧑‍💼","office worker"],["👴","old man"],["👵","old woman"],
      ["🧓","older person"],["👊","oncoming fist"],["🚔","oncoming police car"],["📂","open file folder"],["👐","open hands"],["🧡","orange heart"],
      ["🫳","palm down hand"],["🌴","palm tree"],["🫴","palm up hand"],["🤲","palms up together"],["🍐","pear"],["🧑‍🤝‍🧑","people holding hands"],
      ["👯","people with bunny ears"],["🤼","people wrestling"],["🧑","person"],["🧑‍🦲","person bald"],["🧔","person beard"],["🚴","person biking"],
      ["⛹️","person bouncing ball"],["🙇","person bowing"],["🤸","person cartwheeling"],["🧗","person climbing"],["🧑‍🍼","person feeding baby"],["🤺","person fencing"],
      ["🙍","person frowning"],["🙅","person gesturing NO"],["🙆","person gesturing OK"],["💆","person getting massage"],["🏌️","person golfing"],["🛌","person in bed"],
      ["🧘","person in lotus position"],["🧑‍🦽","person in manual wheelchair"],["🧑‍🦽‍➡️","person in manual wheelchair facing right"],["🧑‍🦼","person in motorized wheelchair"],["🧑‍🦼‍➡️","person in motorized wheelchair facing right"],["🧖","person in steamy room"],
      ["🕴️","person in suit levitating"],["🤵","person in tuxedo"],["🤹","person juggling"],["🧎","person kneeling"],["🧎‍➡️","person kneeling facing right"],["🏋️","person lifting weights"],
      ["🚵","person mountain biking"],["🤾","person playing handball"],["🤽","person playing water polo"],["🙎","person pouting"],["🙋","person raising hand"],["🚣","person rowing boat"],
      ["🏃","person running"],["🏃‍➡️","person running facing right"],["🤷","person shrugging"],["🧍","person standing"],["🏄","person surfing"],["🏊","person swimming"],
      ["🛀","person taking bath"],["💁","person tipping hand"],["🚶","person walking"],["🚶‍➡️","person walking facing right"],["👳","person wearing turban"],["🫅","person with crown"],
      ["👰","person with veil"],["🧑‍🦯","person with white cane"],["🧑‍🦯‍➡️","person with white cane facing right"],["🐽","pig nose"],["🧑‍✈️","pilot"],["🤌","pinched fingers"],
      ["🤏","pinching hand"],["🩷","pink heart"],["🐻‍❄️","polar bear"],["🚓","police car"],["🚨","police car light"],["👮","police officer"],
      ["🍗","poultry leg"],["🫃","pregnant man"],["🫄","pregnant person"],["🤰","pregnant woman"],["🤴","prince"],["👸","princess"],
      ["💜","purple heart"],["🤚","raised back of hand"],["✊","raised fist"],["✋","raised hand"],["🙌","raising hands"],["❤️","red heart"],
      ["⛑️","rescue worker\u2019s helmet"],["💞","revolving hearts"],["🤜","right-facing fist"],["🫱","rightwards hand"],["🫸","rightwards pushing hand"],["🫺","rightwards thumb sign"],
      ["🏉","rugby football"],["🧑‍🔬","scientist"],["🤳","selfie"],["🧑‍🎤","singer"],["🐌","snail"],["☃️","snowman"],
      ["⛄","snowman without snow"],["💖","sparkling heart"],["🧑‍🎓","student"],["🧑‍🏫","teacher"],["🍵","teacup without handle"],["🧸","teddy bear"],
      ["👎","thumbs down"],["👍","thumbs up"],["👅","tongue"],["🦷","tooth"],["🪥","toothbrush"],["🧌","troll"],
      ["🚎","trolleybus"],["🪊","trombone"],["💕","two hearts"],["🧛","vampire"],["✌️","victory hand"],["🌊","water wave"],
      ["👋","waving hand"],["🙀","weary cat"],["☸️","wheel of dharma"],["🤍","white heart"],["👩","woman"],["👫","woman and man holding hands"],
      ["👩‍🎨","woman artist"],["👩‍🚀","woman astronaut"],["👩‍🦲","woman bald"],["🧔‍♀️","woman beard"],["🚴‍♀️","woman biking"],["⛹️‍♀️","woman bouncing ball"],
      ["🙇‍♀️","woman bowing"],["🤸‍♀️","woman cartwheeling"],["🧗‍♀️","woman climbing"],["👷‍♀️","woman construction worker"],["👩‍🍳","woman cook"],["💃","woman dancing"],
      ["🕵️‍♀️","woman detective"],["🧝‍♀️","woman elf"],["👩‍🏭","woman factory worker"],["🧚‍♀️","woman fairy"],["👩‍🌾","woman farmer"],["👩‍🍼","woman feeding baby"],
      ["👩‍🚒","woman firefighter"],["🙍‍♀️","woman frowning"],["🧞‍♀️","woman genie"],["🙅‍♀️","woman gesturing NO"],["🙆‍♀️","woman gesturing OK"],["💆‍♀️","woman getting massage"],
      ["🏌️‍♀️","woman golfing"],["💂‍♀️","woman guard"],["👩‍⚕️","woman health worker"],["🧘‍♀️","woman in lotus position"],["👩‍🦽","woman in manual wheelchair"],["👩‍🦽‍➡️","woman in manual wheelchair facing right"],
      ["👩‍🦼","woman in motorized wheelchair"],["👩‍🦼‍➡️","woman in motorized wheelchair facing right"],["🧖‍♀️","woman in steamy room"],["🤵‍♀️","woman in tuxedo"],["👩‍⚖️","woman judge"],["🤹‍♀️","woman juggling"],
      ["🧎‍♀️","woman kneeling"],["🧎‍♀️‍➡️","woman kneeling facing right"],["🏋️‍♀️","woman lifting weights"],["🧙‍♀️","woman mage"],["👩‍🔧","woman mechanic"],["🚵‍♀️","woman mountain biking"],
      ["👩‍💼","woman office worker"],["👩‍✈️","woman pilot"],["🤾‍♀️","woman playing handball"],["🤽‍♀️","woman playing water polo"],["👮‍♀️","woman police officer"],["🙎‍♀️","woman pouting"],
      ["🙋‍♀️","woman raising hand"],["🚣‍♀️","woman rowing boat"],["🏃‍♀️","woman running"],["🏃‍♀️‍➡️","woman running facing right"],["👩‍🔬","woman scientist"],["🤷‍♀️","woman shrugging"],
      ["👩‍🎤","woman singer"],["🧍‍♀️","woman standing"],["👩‍🎓","woman student"],["🦸‍♀️","woman superhero"],["🦹‍♀️","woman supervillain"],["🏄‍♀️","woman surfing"],
      ["🏊‍♀️","woman swimming"],["👩‍🏫","woman teacher"],["👩‍💻","woman technologist"],["💁‍♀️","woman tipping hand"],["🧛‍♀️","woman vampire"],["🚶‍♀️","woman walking"],
      ["🚶‍♀️‍➡️","woman walking facing right"],["👳‍♀️","woman wearing turban"],["🧕","woman with headscarf"],["👰‍♀️","woman with veil"],["👩‍🦯","woman with white cane"],["👩‍🦯‍➡️","woman with white cane facing right"],
      ["🧟‍♀️","woman zombie"],["👢","woman\u2019s boot"],["👚","woman\u2019s clothes"],["👒","woman\u2019s hat"],["👡","woman\u2019s sandal"],["👭","women holding hands"],
      ["👯‍♀️","women with bunny ears"],["🤼‍♀️","women wrestling"],["✍️","writing hand"],["💛","yellow heart"],["🧟","zombie"],
    ],
  },
  {
    name: "Nature",
    items: [
      ["🎄","Christmas tree"],["🈸","Japanese application button"],["🦖","T-Rex"],["🐜","ant"],["📶","antenna bars"],["🦡","badger"],
      ["🦇","bat"],["🔋","battery"],["🏖️","beach with umbrella"],["🍺","beer mug"],["🪲","beetle"],["🐦","bird"],
      ["🐦‍⬛","black bird"],["🐈‍⬛","black cat"],["🌼","blossom"],["🐡","blowfish"],["🐗","boar"],["💐","bouquet"],
      ["🎳","bowling"],["🍄‍🟫","brown mushroom"],["🐛","bug"],["🚅","bullet train"],["🦋","butterfly"],["🌵","cactus"],
      ["🐪","camel"],["🎠","carousel horse"],["🐈","cat"],["🌸","cherry blossom"],["🌰","chestnut"],["🐔","chicken"],
      ["🍻","clinking beer mugs"],["📋","clipboard"],["🌂","closed umbrella"],["☁️","cloud"],["🌩️","cloud with lightning"],["⛈️","cloud with lightning and rain"],
      ["🌧️","cloud with rain"],["🌨️","cloud with snow"],["☄️","comet"],["🖱️","computer mouse"],["🐄","cow"],["🦀","crab"],
      ["🌙","crescent moon"],["🐊","crocodile"],["🥐","croissant"],["🍮","custard"],["🌀","cyclone"],["🌳","deciduous tree"],
      ["🦌","deer"],["🐕","dog"],["🐬","dolphin"],["🔯","dotted six-pointed star"],["💧","droplet"],["🦆","duck"],
      ["🦅","eagle"],["🍆","eggplant"],["✴️","eight-pointed star"],["🐘","elephant"],["🌲","evergreen tree"],["🍂","fallen leaf"],
      ["🫯","fight cloud"],["🔥","fire"],["🚒","fire engine"],["🧯","fire extinguisher"],["🧨","firecracker"],["🎆","fireworks"],
      ["🌓","first quarter moon"],["🐟","fish"],["🍥","fish cake with swirl"],["🎣","fishing pole"],["🦩","flamingo"],["🎴","flower playing cards"],
      ["🌫️","fog"],["🌁","foggy"],["🍀","four leaf clover"],["🦊","fox"],["🐸","frog"],["🌕","full moon"],
      ["🦒","giraffe"],["🌎","globe showing Americas"],["🌏","globe showing Asia-Australia"],["🌍","globe showing Europe-Africa"],["🌐","globe with meridians"],["🌟","glowing star"],
      ["🐐","goat"],["🦍","gorilla"],["🦮","guide dog"],["🐹","hamster"],["🌿","herb"],["🌺","hibiscus"],
      ["🚄","high-speed train"],["🦛","hippopotamus"],["🐝","honeybee"],["🐎","horse"],["🏇","horse racing"],["🌭","hot dog"],
      ["🪪","identification card"],["🎃","jack-o-lantern"],["🪼","jellyfish"],["🦘","kangaroo"],["⌨️","keyboard"],["🐨","koala"],
      ["🐞","lady beetle"],["🌗","last quarter moon"],["🍃","leaf fluttering in wind"],["🪾","leafless tree"],["🥬","leafy green"],["🐆","leopard"],
      ["🦁","lion"],["🦎","lizard"],["🪫","low battery"],["🍁","maple leaf"],["🫌","monarch butterfly"],["🥮","moon cake"],
      ["🎑","moon viewing ceremony"],["🐁","mouse"],["🪤","mouse trap"],["🍄","mushroom"],["🎹","musical keyboard"],["🌑","new moon"],
      ["🌃","night with stars"],["🚱","non-potable water"],["🐙","octopus"],["🦦","otter"],["🦉","owl"],["🐼","panda"],
      ["🦜","parrot"],["🦚","peacock"],["🐧","penguin"],["🐖","pig"],["🚰","potable water"],["🪴","potted plant"],
      ["😾","pouting cat"],["🐇","rabbit"],["🌈","rainbow"],["🏮","red paper lantern"],["🦏","rhinoceros"],["🌹","rose"],
      ["🏵️","rosette"],["📡","satellite antenna"],["🦂","scorpion"],["🌱","seedling"],["🐕‍🦺","service dog"],["🦈","shark"],
      ["🌠","shooting star"],["🛹","skateboard"],["🦨","skunk"],["🦥","sloth"],["🐍","snake"],["🏔️","snow-capped mountain"],
      ["🏂","snowboarder"],["❄️","snowflake"],["❇️","sparkle"],["🎇","sparkler"],["✨","sparkles"],["🕷️","spider"],
      ["🕸️","spider web"],["🐚","spiral shell"],["🐳","spouting whale"],["🦑","squid"],["⭐","star"],["☪️","star and crescent"],
      ["✡️","star of David"],["🤩","star-struck"],["🍜","steaming bowl"],["☀️","sun"],["⛅","sun behind cloud"],["🌥️","sun behind large cloud"],
      ["🌦️","sun behind rain cloud"],["🌤️","sun behind small cloud"],["🌻","sunflower"],["🕶️","sunglasses"],["🌅","sunrise"],["🌄","sunrise over mountains"],
      ["🌇","sunset"],["🦢","swan"],["💦","sweat droplets"],["🎋","tanabata tree"],["🐅","tiger"],["🌪️","tornado"],
      ["🚆","train"],["🐠","tropical fish"],["🌷","tulip"],["🐢","turtle"],["🐫","two-hump camel"],["☂️","umbrella"],
      ["⛱️","umbrella on ground"],["☔","umbrella with rain drops"],["🦄","unicorn"],["🌘","waning crescent moon"],["🌖","waning gibbous moon"],["🐃","water buffalo"],
      ["🚾","water closet"],["🔫","water pistol"],["🍉","watermelon"],["🌒","waxing crescent moon"],["🌔","waxing gibbous moon"],["🐋","whale"],
      ["💮","white flower"],["🥀","wilted flower"],["🎐","wind chime"],["🪟","window"],["🐺","wolf"],["🦓","zebra"],
    ],
  },
  {
    name: "Food",
    items: [
      ["♑","Capricorn"],["🥑","avocado"],["🥓","bacon"],["🥯","bagel"],["🥖","baguette bread"],["🍌","banana"],
      ["🫑","bell pepper"],["🍱","bento box"],["🎂","birthday cake"],["🍾","bottle with popping cork"],["🍞","bread"],["🥦","broccoli"],
      ["🧋","bubble tea"],["🌯","burrito"],["🧈","butter"],["🍬","candy"],["🥫","canned food"],["🥕","carrot"],
      ["🧀","cheese wedge"],["🍒","cherries"],["🍫","chocolate bar"],["🥢","chopsticks"],["🥂","clinking glasses"],["🍸","cocktail glass"],
      ["🥥","coconut"],["🥒","cucumber"],["🥤","cup with straw"],["🧁","cupcake"],["🍛","curry rice"],["🥩","cut of meat"],
      ["🍡","dango"],["🍩","doughnut"],["🥟","dumpling"],["🥚","egg"],["🧆","falafel"],["🫓","flatbread"],
      ["🍴","fork and knife"],["🍽️","fork and knife with plate"],["🍟","french fries"],["🧄","garlic"],["🥛","glass of milk"],["🍇","grapes"],
      ["🍏","green apple"],["🥗","green salad"],["🍔","hamburger"],["🍯","honey pot"],["🌶️","hot pepper"],["🍨","ice cream"],
      ["🫙","jar"],["🔪","kitchen knife"],["🥝","kiwi fruit"],["🔶","large orange diamond"],["🍋","lemon"],["🍭","lollipop"],
      ["🧴","lotion bottle"],["🧉","mate"],["🍈","melon"],["🌌","milky way"],["🪺","nest with eggs"],["🍢","oden"],
      ["🩱","one-piece swimsuit"],["🧅","onion"],["📙","orange book"],["🟠","orange circle"],["🟧","orange square"],["🦪","oyster"],
      ["🥞","pancakes"],["🍑","peach"],["🥜","peanuts"],["🥧","pie"],["🍍","pineapple"],["🍕","pizza"],
      ["🍿","popcorn"],["🥔","potato"],["🥨","pretzel"],["🧩","puzzle piece"],["🍎","red apple"],["🍙","rice ball"],
      ["🍘","rice cracker"],["🍠","roasted sweet potato"],["🍶","sake"],["🧂","salt"],["🥪","sandwich"],["🌾","sheaf of rice"],
      ["🍰","shortcake"],["🔸","small orange diamond"],["🍦","soft ice cream"],["🍝","spaghetti"],["🍓","strawberry"],["🥙","stuffed flatbread"],
      ["🍣","sushi"],["🌮","taco"],["🥡","takeout box"],["🫔","tamale"],["🫖","teapot"],["🍅","tomato"],
      ["🍹","tropical drink"],["🥃","tumbler glass"],["🧇","waffle"],["🍷","wine glass"],
    ],
  },
  {
    name: "Activity",
    items: [
      ["🥇","1st place medal"],["🥈","2nd place medal"],["🥉","3rd place medal"],["🎎","Japanese dolls"],["🪗","accordion"],["🎟️","admission tickets"],
      ["🏸","badminton"],["🎈","balloon"],["🪕","banjo"],["⚾","baseball"],["🏀","basketball"],["🥊","boxing glove"],
      ["♟️","chess pawn"],["🎪","circus tent"],["♣️","club suit"],["🎊","confetti ball"],["🦗","cricket"],["🏏","cricket game"],
      ["🥌","curling stone"],["♦️","diamond suit"],["🤿","diving mask"],["💵","dollar banknote"],["🥁","drum"],["🏑","field hockey"],
      ["🎲","game die"],["🥅","goal net"],["🎸","guitar"],["🎧","headphone"],["💲","heavy dollar sign"],["🏒","ice hockey"],
      ["⛸️","ice skate"],["🕹️","joystick"],["🪁","kite"],["🥍","lacrosse"],["🪘","long drum"],["🀄","mahjong red dragon"],
      ["🥋","martial arts uniform"],["🎤","microphone"],["🎖️","military medal"],["🎵","musical note"],["🎶","musical notes"],["🎼","musical score"],
      ["🪆","nesting dolls"],["🛢️","oil drum"],["🎉","party popper"],["🎭","performing arts"],["🏓","ping pong"],["🛐","place of worship"],
      ["📻","radio"],["🔘","radio button"],["☢️","radioactive"],["♻️","recycling symbol"],["🎗️","reminder ribbon"],["🎀","ribbon"],
      ["🎷","saxophone"],["⛷️","skier"],["🎿","skis"],["🛷","sled"],["🎰","slot machine"],["⚽","soccer ball"],
      ["🥎","softball"],["♠️","spade suit"],["💬","speech balloon"],["🏅","sports medal"],["🎙️","studio microphone"],["🎾","tennis"],
      ["💭","thought balloon"],["🎫","ticket"],["🏆","trophy"],["🎺","trumpet"],["🎮","video game"],["🎻","violin"],
      ["🏐","volleyball"],["🎁","wrapped gift"],
    ],
  },
  {
    name: "Travel",
    items: [
      ["🏯","Japanese castle"],["🈺","Japanese open for business button"],["🏣","Japanese post office"],["🗽","Statue of Liberty"],["🗼","Tokyo tower"],["🚡","aerial tramway"],
      ["✈️","airplane"],["🛬","airplane arrival"],["🛫","airplane departure"],["🚑","ambulance"],["⚓","anchor"],["🏦","bank"],
      ["🚲","bicycle"],["🌉","bridge at night"],["🏗️","building construction"],["🚌","bus"],["🚏","bus stop"],["👤","bust in silhouette"],
      ["👥","busts in silhouette"],["🏕️","camping"],["🛶","canoe"],["🗃️","card file box"],["📇","card index"],["🗂️","card index dividers"],
      ["🎏","carp streamer"],["🪚","carpentry saw"],["🏰","castle"],["⛪","church"],["🏙️","cityscape"],["🌆","cityscape at dusk"],
      ["🏛️","classical building"],["🧭","compass"],["🚧","construction"],["🏪","convenience store"],["💳","credit card"],["🚚","delivery truck"],
      ["🏬","department store"],["🏚️","derelict house"],["🏜️","desert"],["🏝️","desert island"],["💶","euro banknote"],["🏭","factory"],
      ["🎡","ferris wheel"],["⛴️","ferry"],["⛲","fountain"],["🖋️","fountain pen"],["⛽","fuel pump"],["🚁","helicopter"],
      ["🛕","hindu temple"],["🚥","horizontal traffic light"],["🏥","hospital"],["🏨","hotel"],["🏠","house"],["🏡","house with garden"],
      ["🏘️","houses"],["🕋","kaaba"],["🛴","kick scooter"],["🛅","left luggage"],["🛙","lighthouse"],["🏩","love hotel"],
      ["🧳","luggage"],["🗾","map of Japan"],["🚇","metro"],["🚐","minibus"],["🚝","monorail"],["🕌","mosque"],
      ["🛥️","motor boat"],["🛵","motor scooter"],["🏍️","motorcycle"],["🦼","motorized wheelchair"],["🛣️","motorway"],["⛰️","mountain"],
      ["🚠","mountain cableway"],["🚞","mountain railway"],["🚳","no bicycles"],["🏢","office building"],["🚍","oncoming bus"],["🚖","oncoming taxi"],
      ["🪂","parachute"],["🛳️","passenger ship"],["🛻","pickup truck"],["🪧","placard"],["🏤","post office"],["💷","pound banknote"],
      ["🏎️","racing car"],["🚃","railway car"],["🛤️","railway track"],["🚀","rocket"],["🎢","roller coaster"],["⛵","sailboat"],
      ["🛰️","satellite"],["🧣","scarf"],["🏫","school"],["🚢","ship"],["🛒","shopping cart"],["🛩️","small airplane"],
      ["🚤","speedboat"],["🏟️","stadium"],["🚉","station"],["🚟","suspension railway"],["🕍","synagogue"],["🚕","taxi"],
      ["⛺","tent"],["🚜","tractor"],["🚊","tram"],["🚋","tram car"],["🚦","vertical traffic light"],["🌋","volcano"],
      ["🛞","wheel"],["♿","wheelchair symbol"],["🗺️","world map"],["💴","yen banknote"],
    ],
  },
  {
    name: "Objects",
    items: [
      ["♊","Gemini"],["🧮","abacus"],["🩹","adhesive bandage"],["⚗️","alembic"],["🪓","axe"],["🎒","backpack"],
      ["⚖️","balance scale"],["🩰","ballet shoes"],["📊","bar chart"],["🧺","basket"],["🛏️","bed"],["🔔","bell"],
      ["🔕","bell with slash"],["🛎️","bellhop bell"],["👙","bikini"],["📘","blue book"],["💣","bomb"],["🔖","bookmark"],
      ["📑","bookmark tabs"],["📚","books"],["💼","briefcase"],["🩲","briefs"],["⛓️‍💥","broken chain"],["🧹","broom"],
      ["🫧","bubbles"],["🪣","bucket"],["📅","calendar"],["📷","camera"],["📸","camera with flash"],["🕯️","candle"],
      ["⛓️","chains"],["📉","chart decreasing"],["📈","chart increasing"],["💹","chart increasing with yen"],["🚬","cigarette"],["🗜️","clamp"],
      ["🔃","clockwise vertical arrows"],["📕","closed book"],["👝","clutch bag"],["🧥","coat"],["⚰️","coffin"],["🪙","coin"],
      ["💽","computer disk"],["🔄","counterclockwise arrows button"],["🖍️","crayon"],["⚔️","crossed swords"],["👑","crown"],["🩼","crutch"],
      ["🗡️","dagger"],["🖥️","desktop computer"],["🧬","dna"],["🫏","donkey"],["🚪","door"],["👗","dress"],
      ["📧","e-mail"],["🕗","eight o\u2019clock"],["🔌","electric plug"],["🛗","elevator"],["🕚","eleven o\u2019clock"],["✉️","envelope"],
      ["📩","envelope with arrow"],["🗄️","file cabinet"],["🎞️","film frames"],["📽️","film projector"],["🕔","five o\u2019clock"],["🔦","flashlight"],
      ["🥿","flat shoe"],["💾","floppy disk"],["🕓","four o\u2019clock"],["⚱️","funeral urn"],["💎","gem stone"],["👓","glasses"],
      ["🧤","gloves"],["🥽","goggles"],["📗","green book"],["🪮","hair pick"],["🔨","hammer"],["⚒️","hammer and pick"],
      ["🛠️","hammer and wrench"],["🐣","hatching chick"],["🪦","headstone"],["👠","high-heeled shoe"],["🥾","hiking boot"],["🪝","hook"],
      ["♨️","hot springs"],["⌛","hourglass done"],["⏳","hourglass not done"],["📥","inbox tray"],["📨","incoming envelope"],["👖","jeans"],
      ["🔑","key"],["#️⃣","keycap #"],["*️⃣","keycap *"],["0️⃣","keycap 0"],["1️⃣","keycap 1"],["🔟","keycap 10"],
      ["2️⃣","keycap 2"],["3️⃣","keycap 3"],["4️⃣","keycap 4"],["5️⃣","keycap 5"],["6️⃣","keycap 6"],["7️⃣","keycap 7"],
      ["8️⃣","keycap 8"],["9️⃣","keycap 9"],["👘","kimono"],["🪢","knot"],["🥼","lab coat"],["🏷️","label"],
      ["🪜","ladder"],["💻","laptop"],["📒","ledger"],["💡","light bulb"],["🔗","link"],["🖇️","linked paperclips"],
      ["💄","lipstick"],["🔒","locked"],["🔐","locked with key"],["🔏","locked with pen"],["📢","loudspeaker"],["🧲","magnet"],
      ["🔍","magnifying glass tilted left"],["🔎","magnifying glass tilted right"],["📣","megaphone"],["📝","memo"],["🔬","microscope"],["🪖","military helmet"],
      ["🪞","mirror"],["🪩","mirror ball"],["🗿","moai"],["📱","mobile phone"],["📴","mobile phone off"],["📲","mobile phone with arrow"],
      ["💰","money bag"],["💸","money with wings"],["🎥","movie camera"],["👔","necktie"],["📰","newspaper"],["🕘","nine o\u2019clock"],
      ["🚯","no littering"],["📵","no mobile phones"],["📓","notebook"],["📔","notebook with decorative cover"],["🗝️","old key"],["🕐","one o\u2019clock"],
      ["📖","open book"],["💿","optical disk"],["📤","outbox tray"],["📦","package"],["📄","page facing up"],["📃","page with curl"],
      ["📟","pager"],["🖌️","paintbrush"],["📎","paperclip"],["🖊️","pen"],["✏️","pencil"],["🧫","petri dish"],
      ["⛏️","pick"],["🫝","pickle"],["💊","pill"],["🪠","plunger"],["🫗","pouring liquid"],["🖨️","printer"],
      ["👛","purse"],["📌","pushpin"],["🪒","razor"],["🧾","receipt"],["🧧","red envelope"],["💍","ring"],
      ["🛟","ring buoy"],["🪐","ringed planet"],["🗞️","rolled-up newspaper"],["📍","round pushpin"],["🎽","running shirt"],["👟","running shoe"],
      ["🦺","safety vest"],["🥻","sari"],["✂️","scissors"],["🪛","screwdriver"],["🕖","seven o\u2019clock"],["🪡","sewing needle"],
      ["🛡️","shield"],["🩳","shorts"],["🚿","shower"],["🕕","six o\u2019clock"],["🧼","soap"],["🧦","socks"],
      ["🗓️","spiral calendar"],["🧽","sponge"],["🩺","stethoscope"],["⏱️","stopwatch"],["📏","straight ruler"],["💉","syringe"],
      ["👕","t-shirt"],["☎️","telephone"],["📞","telephone receiver"],["🔭","telescope"],["🕙","ten o\u2019clock"],["🧪","test tube"],
      ["🩴","thong sandal"],["🧵","thread"],["🕒","three o\u2019clock"],["⏲️","timer clock"],["🚽","toilet"],["🧰","toolbox"],
      ["🎩","top hat"],["📐","triangular ruler"],["🦃","turkey"],["🕛","twelve o\u2019clock"],["🕑","two o\u2019clock"],["🔓","unlocked"],
      ["📹","video camera"],["📼","videocassette"],["🗑️","wastebasket"],["⌚","watch"],["🔧","wrench"],["🧶","yarn"],
    ],
  },
  {
    name: "Symbols",
    items: [
      ["🅰️","A button (blood type)"],["🆎","AB button (blood type)"],["🏧","ATM sign"],["♒","Aquarius"],["♈","Aries"],["🅱️","B button (blood type)"],
      ["🔙","BACK arrow"],["🆑","CL button"],["🆒","COOL button"],["♋","Cancer"],["🔚","END arrow"],["🆓","FREE button"],
      ["🆔","ID button"],["🉑","Japanese acceptable button"],["🉐","Japanese bargain button"],["㊗️","Japanese congratulations button"],["🈹","Japanese discount button"],["🈚","Japanese free of charge button"],
      ["🈁","Japanese here button"],["🈷️","Japanese monthly amount button"],["🈵","Japanese no vacancy button"],["🈶","Japanese not free of charge button"],["🈴","Japanese passing grade button"],["🈲","Japanese prohibited button"],
      ["🈯","Japanese reserved button"],["㊙️","Japanese secret button"],["🈂️","Japanese service charge button"],["🔰","Japanese symbol for beginner"],["🈳","Japanese vacancy button"],["♌","Leo"],
      ["♎","Libra"],["🤶","Mrs. Claus"],["🧑‍🎄","Mx Claus"],["🆕","NEW button"],["🆖","NG button"],["🅾️","O button (blood type)"],
      ["🆗","OK button"],["🔛","ON! arrow"],["⛎","Ophiuchus"],["🅿️","P button"],["♓","Pisces"],["🔜","SOON arrow"],
      ["🆘","SOS button"],["♐","Sagittarius"],["♏","Scorpio"],["🔝","TOP arrow"],["♉","Taurus"],["🆙","UP! button"],
      ["🆚","VS button"],["♍","Virgo"],["💤","ZZZ"],["🏺","amphora"],["💢","anger symbol"],["🚛","articulated lorry"],
      ["⚛️","atom symbol"],["🛺","auto rickshaw"],["🚗","automobile"],["🛄","baggage claim"],["🗳️","ballot box with ballot"],["💈","barber pole"],
      ["🫘","beans"],["🦫","beaver"],["🧢","billed cap"],["☣️","biohazard"],["🦬","bison"],["🫦","biting lip"],
      ["⚫","black circle"],["⬛","black large square"],["◼️","black medium square"],["◾","black medium-small square"],["✒️","black nib"],["▪️","black small square"],
      ["🔲","black square button"],["🔵","blue circle"],["🟦","blue square"],["🫐","blueberries"],["🪃","boomerang"],["🏹","bow and arrow"],
      ["🧱","brick"],["🔆","bright button"],["🟤","brown circle"],["🟫","brown square"],["🪑","chair"],["☑️","check box with check"],
      ["✔️","check mark"],["✅","check mark button"],["🐿️","chipmunk"],["🎦","cinema"],["Ⓜ️","circled M"],["🪳","cockroach"],
      ["💥","collision"],["🎛️","control knobs"],["©️","copyright"],["🪸","coral"],["🛋️","couch and lamp"],["❌","cross mark"],
      ["❎","cross mark button"],["➰","curly loop"],["💱","currency exchange"],["🛃","customs"],["💨","dashing away"],["💠","diamond with a dot"],
      ["🔅","dim button"],["➗","divide"],["🪔","diya lamp"],["💫","dizzy"],["🦤","dodo"],["➿","double curly loop"],
      ["‼️","double exclamation mark"],["🕊️","dove"],["⬇️","down arrow"],["↙️","down-left arrow"],["↘️","down-right arrow"],["🔽","downwards button"],
      ["🐉","dragon"],["🩸","drop of blood"],["📀","dvd"],["✳️","eight-spoked asterisk"],["🕣","eight-thirty"],["⏏️","eject button"],
      ["🕦","eleven-thirty"],["🪹","empty nest"],["🪌","eraser"],["🐑","ewe"],["⁉️","exclamation question mark"],["🤯","exploding head"],
      ["⏬","fast down button"],["⏪","fast reverse button"],["⏫","fast up button"],["⏩","fast-forward button"],["📠","fax machine"],["🪶","feather"],
      ["♀️","female sign"],["🕠","five-thirty"],["⚜️","fleur-de-lis"],["💪","flexed biceps"],["🪈","flute"],["🪰","fly"],
      ["🥏","flying disc"],["🛸","flying saucer"],["🫕","fondue"],["🕟","four-thirty"],["🖼️","framed picture"],["🫚","ginger root"],
      ["🪿","goose"],["🎓","graduation cap"],["🟢","green circle"],["🟩","green square"],["🫈","hairy creature"],["🪬","hamsa"],
      ["🪉","harp"],["🙂‍↔️","head shaking horizontally"],["🙂‍↕️","head shaking vertically"],["🟰","heavy equals sign"],["🦔","hedgehog"],["⚡","high voltage"],
      ["🕳️","hole"],["⭕","hollow red circle"],["💯","hundred points"],["🛖","hut"],["🪻","hyacinth"],["🧊","ice"],
      ["🫵","index pointing at the viewer"],["☝️","index pointing up"],["♾️","infinity"],["ℹ️","information"],["🔤","input latin letters"],["🔡","input latin lowercase"],
      ["🔠","input latin uppercase"],["🔢","input numbers"],["🔣","input symbols"],["🃏","joker"],["🛘","landslide"],["🔷","large blue diamond"],
      ["⏮️","last track button"],["✝️","latin cross"],["⬅️","left arrow"],["↪️","left arrow curving right"],["🗨️","left speech bubble"],["↔️","left-right arrow"],
      ["🎚️","level slider"],["🚈","light rail"],["🍋‍🟩","lime"],["🚮","litter in bin sign"],["🦙","llama"],["🦞","lobster"],
      ["🚂","locomotive"],["🪷","lotus"],["💌","love letter"],["🤟","love-you gesture"],["🪄","magic wand"],["♂️","male sign"],
      ["🦣","mammoth"],["🪇","maracas"],["⚕️","medical symbol"],["🕎","menorah"],["🚹","men\u2019s room"],["🧜‍♀️","mermaid"],
      ["🪋","meteor"],["🦠","microbe"],["➖","minus"],["🫎","moose"],["🦟","mosquito"],["🗻","mount fuji"],
      ["✖️","multiply"],["🔇","muted speaker"],["📛","name badge"],["🏞️","national park"],["🧿","nazar amulet"],["⏭️","next track button"],
      ["🕤","nine-thirty"],["🥷","ninja"],["⛔","no entry"],["🔞","no one under eighteen"],["🚷","no pedestrians"],["🚭","no smoking"],
      ["🔩","nut and bolt"],["🫒","olive"],["🕉️","om"],["🚘","oncoming automobile"],["🕜","one-thirty"],["🦧","orangutan"],
      ["🫍","orca"],["☦️","orthodox cross"],["🐂","ox"],["〽️","part alternation mark"],["🛂","passport control"],["⏸️","pause button"],
      ["🐾","paw prints"],["🫛","pea pod"],["☮️","peace symbol"],["🐦‍🔥","phoenix"],["🎍","pine decoration"],["🪅","pi\u00f1ata"],
      ["▶️","play button"],["⏯️","play or pause button"],["🛝","playground slide"],["➕","plus"],["📯","postal horn"],["📮","postbox"],
      ["🍲","pot of food"],["📿","prayer beads"],["🚫","prohibited"],["🟣","purple circle"],["🟪","purple square"],["🦝","raccoon"],
      ["🐏","ram"],["🐀","rat"],["⏺️","record button"],["🔴","red circle"],["❗","red exclamation mark"],["❓","red question mark"],
      ["🟥","red square"],["🔻","red triangle pointed down"],["🔺","red triangle pointed up"],["®️","registered"],["🔁","repeat button"],["🔂","repeat single button"],
      ["🚻","restroom"],["◀️","reverse button"],["🗯️","right anger bubble"],["➡️","right arrow"],["⤵️","right arrow curving down"],["↩️","right arrow curving left"],
      ["⤴️","right arrow curving up"],["🪨","rock"],["🧻","roll of paper"],["🛼","roller skate"],["🐓","rooster"],["🫜","root vegetable"],
      ["🧷","safety pin"],["🦕","sauropod"],["📜","scroll"],["🦭","seal"],["💺","seat"],["🕢","seven-thirty"],
      ["🥘","shallow pan of food"],["☘️","shamrock"],["🍧","shaved ice"],["⛩️","shinto shrine"],["🛍️","shopping bags"],["🪏","shovel"],
      ["🔀","shuffle tracks button"],["🤘","sign of the horns"],["🕡","six-thirty"],["🔹","small blue diamond"],["🔊","speaker high volume"],["🔈","speaker low volume"],
      ["🔉","speaker medium volume"],["🗣️","speaking head"],["🗒️","spiral notepad"],["🫟","splatter"],["🚙","sport utility vehicle"],["⏹️","stop button"],
      ["🛑","stop sign"],["🦸","superhero"],["🦹","supervillain"],["🍊","tangerine"],["🧑‍💻","technologist"],["📺","television"],
      ["🕥","ten-thirty"],["🌡️","thermometer"],["🕞","three-thirty"],["🖲️","trackball"],["™️","trade mark"],["⚧️","transgender symbol"],
      ["🪎","treasure chest"],["🔱","trident emblem"],["🕧","twelve-thirty"],["🕝","two-thirty"],["⬆️","up arrow"],["↕️","up-down arrow"],
      ["↖️","up-left arrow"],["↗️","up-right arrow"],["🔼","upwards button"],["📳","vibration mode"],["🖖","vulcan salute"],["⚠️","warning"],
      ["〰️","wavy dash"],["💒","wedding"],["🦯","white cane"],["⚪","white circle"],["❕","white exclamation mark"],["⬜","white large square"],
      ["◻️","white medium square"],["◽","white medium-small square"],["❔","white question mark"],["▫️","white small square"],["🔳","white square button"],["🪽","wing"],
      ["🛜","wireless"],["🚺","women\u2019s room"],["🪵","wood"],["🪱","worm"],["🩻","x-ray"],["🟡","yellow circle"],
      ["🟨","yellow square"],["☯️","yin yang"],["🪀","yo-yo"],
    ],
  },
  {
    name: "Flags",
    items: [
      ["🇦🇫","Afghanistan"],["🇦🇱","Albania"],["🇩🇿","Algeria"],["🇦🇸","American Samoa"],["🇦🇩","Andorra"],["🇦🇴","Angola"],
      ["🇦🇮","Anguilla"],["🇦🇶","Antarctica"],["🇦🇬","Antigua & Barbuda"],["🇦🇷","Argentina"],["🇦🇲","Armenia"],["🇦🇼","Aruba"],
      ["🇦🇨","Ascension Island"],["🇦🇺","Australia"],["🇦🇹","Austria"],["🇦🇿","Azerbaijan"],["🇧🇸","Bahamas"],["🇧🇭","Bahrain"],
      ["🇧🇩","Bangladesh"],["🇧🇧","Barbados"],["🇧🇾","Belarus"],["🇧🇪","Belgium"],["🇧🇿","Belize"],["🇧🇯","Benin"],
      ["🇧🇲","Bermuda"],["🇧🇹","Bhutan"],["🇧🇴","Bolivia"],["🇧🇦","Bosnia & Herzegovina"],["🇧🇼","Botswana"],["🇧🇻","Bouvet Island"],
      ["🇧🇷","Brazil"],["🇮🇴","British Indian Ocean Territory"],["🇻🇬","British Virgin Islands"],["🇧🇳","Brunei"],["🇧🇬","Bulgaria"],["🇧🇫","Burkina Faso"],
      ["🇧🇮","Burundi"],["🇰🇭","Cambodia"],["🇨🇲","Cameroon"],["🇨🇦","Canada"],["🇮🇨","Canary Islands"],["🇨🇻","Cape Verde"],
      ["🇧🇶","Caribbean Netherlands"],["🇰🇾","Cayman Islands"],["🇨🇫","Central African Republic"],["🇪🇦","Ceuta & Melilla"],["🇹🇩","Chad"],["🇨🇱","Chile"],
      ["🇨🇳","China"],["🇨🇽","Christmas Island"],["🇨🇵","Clipperton Island"],["🇨🇨","Cocos (Keeling) Islands"],["🇨🇴","Colombia"],["🇰🇲","Comoros"],
      ["🇨🇬","Congo-Brazzaville"],["🇨🇩","Congo-Kinshasa"],["🇨🇰","Cook Islands"],["🇨🇷","Costa Rica"],["🇭🇷","Croatia"],["🇨🇺","Cuba"],
      ["🇨🇼","Cura\u00e7ao"],["🇨🇾","Cyprus"],["🇨🇿","Czechia"],["🇨🇮","C\u00f4te d\u2019Ivoire"],["🇩🇰","Denmark"],["🇩🇬","Diego Garcia"],
      ["🇩🇯","Djibouti"],["🇩🇲","Dominica"],["🇩🇴","Dominican Republic"],["🇪🇨","Ecuador"],["🇪🇬","Egypt"],["🇸🇻","El Salvador"],
      ["🏴󠁧󠁢󠁥󠁮󠁧󠁿","England"],["🇬🇶","Equatorial Guinea"],["🇪🇷","Eritrea"],["🇪🇪","Estonia"],["🇸🇿","Eswatini"],["🇪🇹","Ethiopia"],
      ["🇪🇺","European Union"],["🇫🇰","Falkland Islands"],["🇫🇴","Faroe Islands"],["🇫🇯","Fiji"],["🇫🇮","Finland"],["🇫🇷","France"],
      ["🇬🇫","French Guiana"],["🇵🇫","French Polynesia"],["🇹🇫","French Southern and Antarctic Lands"],["🇬🇦","Gabon"],["🇬🇲","Gambia"],["🇬🇪","Georgia"],
      ["🇩🇪","Germany"],["🇬🇭","Ghana"],["🇬🇮","Gibraltar"],["🇬🇷","Greece"],["🇬🇱","Greenland"],["🇬🇩","Grenada"],
      ["🇬🇵","Guadeloupe"],["🇬🇺","Guam"],["🇬🇹","Guatemala"],["🇬🇬","Guernsey"],["🇬🇳","Guinea"],["🇬🇼","Guinea-Bissau"],
      ["🇬🇾","Guyana"],["🇭🇹","Haiti"],["🇭🇲","Heard Island & McDonald Islands"],["🇭🇳","Honduras"],["🇭🇰","Hong Kong SAR China"],["🇭🇺","Hungary"],
      ["🇮🇸","Iceland"],["🇮🇳","India"],["🇮🇩","Indonesia"],["🇮🇷","Iran"],["🇮🇶","Iraq"],["🇮🇪","Ireland"],
      ["🇮🇲","Isle of Man"],["🇮🇱","Israel"],["🇮🇹","Italy"],["🇯🇲","Jamaica"],["🇯🇵","Japan"],["🇯🇪","Jersey"],
      ["🇯🇴","Jordan"],["🇰🇿","Kazakhstan"],["🇰🇪","Kenya"],["🇰🇮","Kiribati"],["🇽🇰","Kosovo"],["🇰🇼","Kuwait"],
      ["🇰🇬","Kyrgyzstan"],["🇱🇦","Laos"],["🇱🇻","Latvia"],["🇱🇧","Lebanon"],["🇱🇸","Lesotho"],["🇱🇷","Liberia"],
      ["🇱🇾","Libya"],["🇱🇮","Liechtenstein"],["🇱🇹","Lithuania"],["🇱🇺","Luxembourg"],["🇲🇴","Macao SAR China"],["🇲🇬","Madagascar"],
      ["🇲🇼","Malawi"],["🇲🇾","Malaysia"],["🇲🇻","Maldives"],["🇲🇱","Mali"],["🇲🇹","Malta"],["🇲🇭","Marshall Islands"],
      ["🇲🇶","Martinique"],["🇲🇷","Mauritania"],["🇲🇺","Mauritius"],["🇾🇹","Mayotte"],["🇲🇽","Mexico"],["🇫🇲","Micronesia"],
      ["🇲🇩","Moldova"],["🇲🇨","Monaco"],["🇲🇳","Mongolia"],["🇲🇪","Montenegro"],["🇲🇸","Montserrat"],["🇲🇦","Morocco"],
      ["🇲🇿","Mozambique"],["🇲🇲","Myanmar (Burma)"],["🇳🇦","Namibia"],["🇳🇷","Nauru"],["🇳🇵","Nepal"],["🇳🇱","Netherlands"],
      ["🇳🇨","New Caledonia"],["🇳🇿","New Zealand"],["🇳🇮","Nicaragua"],["🇳🇪","Niger"],["🇳🇬","Nigeria"],["🇳🇺","Niue"],
      ["🇳🇫","Norfolk Island"],["🇰🇵","North Korea"],["🇲🇰","North Macedonia"],["🇲🇵","Northern Mariana Islands"],["🇳🇴","Norway"],["🇴🇲","Oman"],
      ["🇵🇰","Pakistan"],["🇵🇼","Palau"],["🇵🇸","Palestinian Territories"],["🇵🇦","Panama"],["🇵🇬","Papua New Guinea"],["🇵🇾","Paraguay"],
      ["🇵🇪","Peru"],["🇵🇭","Philippines"],["🇵🇳","Pitcairn Islands"],["🇵🇱","Poland"],["🇵🇹","Portugal"],["🇵🇷","Puerto Rico"],
      ["🇶🇦","Qatar"],["🇷🇴","Romania"],["🇷🇺","Russia"],["🇷🇼","Rwanda"],["🇷🇪","R\u00e9union"],["🇼🇸","Samoa"],
      ["🇸🇲","San Marino"],["🇨🇶","Sark"],["🇸🇦","Saudi Arabia"],["🏴󠁧󠁢󠁳󠁣󠁴󠁿","Scotland"],["🇸🇳","Senegal"],["🇷🇸","Serbia"],
      ["🇸🇨","Seychelles"],["🇸🇱","Sierra Leone"],["🇸🇬","Singapore"],["🇸🇽","Sint Maarten"],["🇸🇰","Slovakia"],["🇸🇮","Slovenia"],
      ["🇸🇧","Solomon Islands"],["🇸🇴","Somalia"],["🇿🇦","South Africa"],["🇬🇸","South Georgia & South Sandwich Islands"],["🇰🇷","South Korea"],["🇸🇸","South Sudan"],
      ["🇪🇸","Spain"],["🇱🇰","Sri Lanka"],["🇧🇱","St. Barth\u00e9lemy"],["🇸🇭","St. Helena Ascension & Tristan da Cunha"],["🇰🇳","St. Kitts & Nevis"],["🇱🇨","St. Lucia"],
      ["🇲🇫","St. Martin"],["🇵🇲","St. Pierre & Miquelon"],["🇻🇨","St. Vincent & Grenadines"],["🇸🇩","Sudan"],["🇸🇷","Suriname"],["🇸🇯","Svalbard & Jan Mayen"],
      ["🇸🇪","Sweden"],["🇨🇭","Switzerland"],["🇸🇾","Syria"],["🇸🇹","S\u00e3o Tom\u00e9 & Pr\u00edncipe"],["🇹🇼","Taiwan"],["🇹🇯","Tajikistan"],
      ["🇹🇿","Tanzania"],["🇹🇭","Thailand"],["🇹🇱","Timor-Leste"],["🇹🇬","Togo"],["🇹🇰","Tokelau"],["🇹🇴","Tonga"],
      ["🇹🇹","Trinidad & Tobago"],["🇹🇦","Tristan da Cunha"],["🇹🇳","Tunisia"],["🇹🇲","Turkmenistan"],["🇹🇨","Turks & Caicos Islands"],["🇹🇻","Tuvalu"],
      ["🇹🇷","T\u00fcrkiye"],["🇺🇲","U.S. Outlying Islands"],["🇻🇮","U.S. Virgin Islands"],["🇺🇬","Uganda"],["🇺🇦","Ukraine"],["🇦🇪","United Arab Emirates"],
      ["🇬🇧","United Kingdom"],["🇺🇳","United Nations"],["🇺🇸","United States"],["🇺🇾","Uruguay"],["🇺🇿","Uzbekistan"],["🇻🇺","Vanuatu"],
      ["🇻🇦","Vatican City"],["🇻🇪","Venezuela"],["🇻🇳","Vietnam"],["🏴󠁧󠁢󠁷󠁬󠁳󠁿","Wales"],["🇼🇫","Wallis & Futuna"],["🇪🇭","Western Sahara"],
      ["🇾🇪","Yemen"],["🇿🇲","Zambia"],["🇿🇼","Zimbabwe"],["🏴","black flag"],["🏁","chequered flag"],["📪","closed mailbox with lowered flag"],
      ["📫","closed mailbox with raised flag"],["🎌","crossed flags"],["⛳","flag in hole"],["📭","open mailbox with lowered flag"],["📬","open mailbox with raised flag"],["🏴‍☠️","pirate flag"],
      ["🏳️‍🌈","rainbow flag"],["🏳️‍⚧️","transgender flag"],["🚩","triangular flag"],["🏳️","white flag"],["🇦🇽","\u00c5land Islands"],
    ],
  },
];

/** Every emoji, flattened, for search across all groups. */
export const EMOJI_ALL: EmojiEntry[] = EMOJI_GROUPS.flatMap((g) => g.items);
