"""Write webui/src/lib/zonecountries.ts: which country each timezone is in.

The timezone picker puts a flag and a country name beside every zone, and
finds "japan" as well as "tokyo". The browser knows the zones but not their
countries, so the table comes from the IANA database, via the tzdata package:

  zone.tab    one line per country and zone ("FR  +4852+00220  Europe/Paris")
  tzdata.zi   its "L" lines are the links, old spellings to new, which the
              browser still lists some of (Asia/Calcutta, Europe/Kiev)

A few old spellings are links to a zone in another country (Pacific/Truk
became a link to Port Moresby when the two clocks agreed), so they are named
here by hand. Zones in no country (UTC, Etc/GMT+3) are left out.

Run it again after a tzdata upgrade: python scripts/gen_zone_countries.py
"""
import os
from pathlib import Path

import tzdata

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "webui" / "src" / "lib" / "zonecountries.ts"
DATA = Path(os.path.dirname(tzdata.__file__)) / "zoneinfo"

# Old spellings whose link now points across a border: the zone they were
# renamed to (in zone.tab) is in the country they name.
RENAMED = {
    "Africa/Asmera": "Africa/Asmara",
    "America/Coral_Harbour": "America/Atikokan",
    "Pacific/Ponape": "Pacific/Pohnpei",
    "Pacific/Truk": "Pacific/Chuuk",
    "Pacific/Yap": "Pacific/Chuuk",
    "America/Virgin": "America/St_Thomas",
}


def main():
    country = {}
    for line in (DATA / "zone.tab").read_text(encoding="utf-8").splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        cc, _coords, zone = line.split("\t")[:3]
        country[zone] = cc

    links = {}
    for line in (DATA / "tzdata.zi").read_text(encoding="utf-8").splitlines():
        if line.startswith("L "):
            _, target, name = line.split()
            links[name] = target

    for name, target in links.items():
        if name in country:
            continue
        cc = country.get(RENAMED.get(name, target))
        if cc:
            country[name] = cc
    for name, renamed in RENAMED.items():
        country[name] = country[renamed]

    by_cc = {}
    for zone, cc in sorted(country.items()):
        by_cc.setdefault(cc, []).append(zone)

    rows = "\n".join(f'  {cc}: "{" ".join(zones)}",' for cc, zones in sorted(by_cc.items()))
    OUT.write_text(f'''/**
 * Which country each timezone is in, for the flags in the timezone picker.
 *
 * Generated by scripts/gen_zone_countries.py from the IANA database (tzdata
 * {tzdata.IANA_VERSION}): zone.tab, with the old spellings the browser still lists
 * (Asia/Calcutta, Europe/Kiev) followed through tzdata.zi's links. Zones in no
 * country (UTC, Etc/GMT+3) are not in it. Do not edit by hand: run the script.
 */
const BY_COUNTRY: Record<string, string> = {{
{rows}
}};

/** Zone to two-letter country code. */
export const ZONE_COUNTRY: Record<string, string> = {{}};
for (const [cc, zones] of Object.entries(BY_COUNTRY)) for (const z of zones.split(" ")) ZONE_COUNTRY[z] = cc;
''', encoding="utf-8", newline="\n")
    print(f"{OUT.relative_to(ROOT)}: {len(country)} zones in {len(by_cc)} countries (tzdata {tzdata.IANA_VERSION})")


if __name__ == "__main__":
    main()
