"""Config.yaml field schema for the Settings UI. Fields marked requires_restart are read once at runner import; everything else applies on the next load_config() (mtime-cached) or via the config_update IPC."""

CONFIG_SCHEMA = [
    {"key": "bot.owner_id", "type": "int", "label": "Owner user ID",
     "section": "General", "requires_restart": True},
    {"key": "bot.prefix", "type": "str", "label": "Command prefix",
     "section": "General", "requires_restart": True},
    {"key": "bot.trigger", "type": "str", "label": "Trigger words (comma-separated)",
     "section": "General", "requires_restart": True},
    {"key": "bot.default_language", "type": "str", "label": "Fallback language",
     "section": "General", "requires_restart": True},
    {"key": "bot.allow_dm", "type": "bool", "label": "Respond in DMs", "section": "Behaviour"},
    {"key": "bot.allow_gc", "type": "bool", "label": "Respond in group chats", "section": "Behaviour"},
    {"key": "bot.allow_server", "type": "bool", "label": "Respond to mentions in servers", "section": "Behaviour"},
    {"key": "bot.realistic_typing", "type": "bool", "label": "Realistic typing", "section": "Behaviour"},
    # How it types, when it does. Defaults, because a config.yaml from before these existed has none of them.
    {"key": "bot.typing.wpm_min", "type": "int", "label": "Slowest typing speed", "section": "Behaviour",
     "min": 5, "max": 300, "default": 30},
    {"key": "bot.typing.wpm_max", "type": "int", "label": "Fastest typing speed", "section": "Behaviour",
     "min": 5, "max": 300, "default": 72},
    {"key": "bot.typing.think_min", "type": "float", "label": "Shortest think before typing",
     "section": "Behaviour", "min": 0, "max": 60, "step": 0.5, "default": 2.0},
    {"key": "bot.typing.think_max", "type": "float", "label": "Longest think before typing",
     "section": "Behaviour", "min": 0, "max": 120, "step": 0.5, "default": 8.0},
    {"key": "bot.typing.pause_chance", "type": "float", "label": "Chance of stopping mid-message",
     "section": "Behaviour", "min": 0, "max": 1, "step": 0.05, "default": 0.35},
    {"key": "bot.typing.max_seconds", "type": "int", "label": "Longest time typing one message",
     "section": "Behaviour", "min": 1, "max": 600, "default": 45},
    {"key": "bot.read_delay_dm_min", "type": "float", "label": "Reading a DM, at least", "section": "Behaviour",
     "min": 0, "max": 120, "step": 0.5, "default": 2.5},
    {"key": "bot.read_delay_dm_max", "type": "float", "label": "Reading a DM, at most", "section": "Behaviour",
     "min": 0, "max": 300, "step": 0.5, "default": 8.0},
    {"key": "bot.read_delay_group_min", "type": "float", "label": "Reading a group chat, at least",
     "section": "Behaviour", "min": 0, "max": 120, "step": 0.5, "default": 1.5},
    {"key": "bot.read_delay_group_max", "type": "float", "label": "Reading a group chat, at most",
     "section": "Behaviour", "min": 0, "max": 300, "step": 0.5, "default": 5.0},
    {"key": "bot.read_delay_server_min", "type": "float", "label": "Reading a server message, at least",
     "section": "Behaviour", "min": 0, "max": 120, "step": 0.5, "default": 1.0},
    {"key": "bot.read_delay_server_max", "type": "float", "label": "Reading a server message, at most",
     "section": "Behaviour", "min": 0, "max": 300, "step": 0.5, "default": 4.0},
    {"key": "bot.batch_messages", "type": "bool", "label": "Batch messages before replying", "section": "Behaviour"},
    {"key": "bot.hold_conversation", "type": "bool", "label": "Hold conversations", "section": "Behaviour"},
    {"key": "bot.reply_ping", "type": "bool", "label": "Ping on replies", "section": "Behaviour"},
    {"key": "bot.disable_mentions", "type": "bool", "label": "Disable mentions",
     "section": "Behaviour"},
    {"key": "bot.anti_age_ban", "type": "bool", "label": "Anti age-ban obfuscation", "section": "Behaviour"},
    {"key": "bot.read_bios", "type": "bool", "label": "Read user bios for context", "section": "Behaviour"},
    {"key": "bot.ignore_chance", "type": "float", "label": "Chance to ignore a message",
     "section": "Humanization", "min": 0.0, "max": 1.0, "step": 0.01, "requires_restart": True},
    {"key": "bot.groq_small_model", "type": "str", "label": "Utility model (memory, language)",
     "section": "General"},
    {"key": "bot.max_reply_tokens", "type": "int", "label": "Longest reply, in tokens",
     "section": "General"},
    {"key": "bot.typo_chance", "type": "float", "label": "Chance of a typo",
     "section": "Humanization", "min": 0.0, "max": 1.0, "step": 0.01},
    {"key": "bot.edit_after_send_chance", "type": "float", "label": "Chance of a typo fix after sending",
     "section": "Humanization", "min": 0.0, "max": 1.0, "step": 0.005},
    {"key": "bot.message_style.mode", "type": "str", "label": "Message style",
     "section": "Humanization"},
    {"key": "bot.reactions.enabled", "type": "bool", "label": "Context-aware emoji reactions",
     "section": "Humanization"},
    {"key": "bot.reactions.react_only_max_ratio", "type": "float", "label": "Max ratio of reaction-only replies",
     "section": "Humanization", "min": 0.0, "max": 1.0, "step": 0.05},
    {"key": "bot.client_profile", "type": "str", "label": "Client profile (web / desktop)",
     "section": "General", "requires_restart": True},
    {"key": "bot.timezone", "type": "str", "label": "Persona timezone",
     "section": "General", "requires_restart": True},
    {"key": "bot.locale", "type": "str", "label": "Persona locale",
     "section": "General", "requires_restart": True},
    # A config from before the choice existed has none, and session.resolve_build_number reads that as custom.
    {"key": "bot.desktop.build_source", "type": "str", "label": "Build number",
     "section": "General", "requires_restart": True, "default": "custom"},
    {"key": "bot.desktop.build_number", "type": "int", "label": "Desktop client build number",
     "section": "General", "requires_restart": True},
    {"key": "bot.night_invisible.enabled", "type": "bool", "label": "Invisible during night hours",
     "section": "Status"},
    {"key": "bot.night_invisible.hours", "type": "str", "label": "Night hours (24h, local, e.g. 2-8)",
     "section": "Status"},
    {"key": "bot.night_invisible.status", "type": "str", "label": "Status during night hours",
     "section": "Status"},
    {"key": "bot.priority_prefix", "type": "str", "label": "Priority prefix",
     "section": "General", "requires_restart": True},
    {"key": "bot.trigger_bypasses_ignore", "type": "bool", "label": "Triggers bypass ignore chance",
     "section": "Humanization", "requires_restart": True},
    {"key": "bot.mention_bypasses_ignore", "type": "bool", "label": "Mentions bypass ignore chance",
     "section": "Humanization", "requires_restart": True},
    {"key": "bot.global_cooldown_enabled", "type": "bool", "label": "Global reply cooldown",
     "section": "Humanization", "requires_restart": True},
    {"key": "bot.global_cooldown_min", "type": "int", "label": "Global cooldown min (s)",
     "section": "Humanization", "min": 5, "max": 600, "requires_restart": True},
    {"key": "bot.global_cooldown_max", "type": "int", "label": "Global cooldown max (s)",
     "section": "Humanization", "min": 5, "max": 3600, "requires_restart": True},
    {"key": "bot.mood.enabled", "type": "bool", "label": "Mood system", "section": "Mood",
     "requires_restart": True},
    {"key": "bot.mood.shift_interval_min", "type": "int", "label": "Mood shift min (s)",
     "section": "Mood", "min": 300, "requires_restart": True},
    {"key": "bot.mood.shift_interval_max", "type": "int", "label": "Mood shift max (s)",
     "section": "Mood", "min": 300, "requires_restart": True},
    {"key": "bot.status.enabled", "type": "bool", "label": "Status cycling",
     "section": "Status", "requires_restart": True},
    {"key": "bot.pictures.enabled", "type": "bool", "label": "Send pictures when asked",
     "section": "Behaviour"},
    # Videos are kept as MP4 and made smaller to fit (app/utils/videos.py); a default, since an older config has none.
    {"key": "bot.pictures.video_max_mb", "type": "int", "label": "Largest video",
     "section": "Behaviour", "default": 10, "min": 1, "max": 500},
    # A look on new pictures, and what the AI may add to one as it sends it (app/utils/looks.py). Drawn by the
    # Pictures panel in Settings (PicturesPanel.svelte); defaults, since a config.yaml from before has none of them.
    {"key": "bot.pictures.auto_look.mode", "type": "str", "label": "Filter on new pictures",
     "section": "Behaviour", "default": "off"},
    {"key": "bot.pictures.auto_look.look", "type": "str", "label": "Filter",
     "section": "Behaviour", "default": "warm"},
    {"key": "bot.pictures.auto_look.looks", "type": "json", "label": "Random filters",
     "section": "Behaviour", "default": []},
    {"key": "bot.pictures.auto_look.strength", "type": "float", "label": "Filter strength",
     "section": "Behaviour", "min": 0.05, "max": 1.0, "step": 0.05, "default": 0.7},
    {"key": "bot.pictures.auto_look.vary", "type": "float", "label": "Vary strength",
     "section": "Behaviour", "min": 0.0, "max": 0.5, "step": 0.05, "default": 0.1},
    {"key": "bot.pictures.touches.accounts", "type": "json", "label": "Accounts that add touches",
     "section": "Behaviour", "default": []},
    {"key": "bot.pictures.touches.chance", "type": "float", "label": "How often it adds something",
     "section": "Behaviour", "min": 0.0, "max": 1.0, "step": 0.05, "default": 0.5},
    {"key": "bot.pictures.touches.kinds", "type": "json", "label": "What it may add",
     "section": "Behaviour", "default": ["caption", "big_text", "time", "day", "emoji", "look"]},
    # "needs": a feature in app/utils/compat.py; the row says so where it does not work.
    {"key": "bot.tts.enabled", "type": "bool", "label": "Voice messages (TTS)", "section": "Behaviour",
     "needs": "voice_messages"},
    # The settings tree named this key but the schema never defined it, so the row was dropped as "a key config.yaml does not have" and the voice model simply had no way to be set from the panel.
    {"key": "bot.groq_tts_model", "type": "str", "label": "Voice model", "section": "Behaviour"},
    {"key": "bot.tts.voice", "type": "str", "label": "Voice", "section": "Behaviour"},
    # "default" fills in for an older config.yaml that has no memory_summary section yet, so the toggle does not read as off while the card is on.
    {"key": "bot.memory_summary.enabled", "type": "bool", "label": "Conversation summaries",
     "section": "Memory", "default": True},
    {"key": "bot.memory_summary.messages", "type": "int", "label": "Messages to read",
     "section": "Memory", "min": 5, "max": 100, "default": 20},
    {"key": "bot.memory_summary.length", "type": "str", "label": "Summary length",
     "section": "Memory", "default": "medium"},
    {"key": "bot.memory_summary.language", "type": "str", "label": "Summary language",
     "section": "Memory", "default": "auto"},
    {"key": "bot.memory_summary.include_my_messages", "type": "bool",
     "label": "Include my messages", "section": "Memory", "default": True},
    {"key": "bot.memory_summary.refresh_minutes", "type": "int",
     "label": "Reuse a summary for (minutes)", "section": "Memory", "min": 0, "max": 1440,
     "default": 30},
    # How a reply is sampled. Blank means "do not send it", so the provider's own
    # default stands; they are floats with ranges rather than free text.
    {"key": "bot.sampling.temperature", "type": "float", "label": "Temperature",
     "section": "Behaviour", "min": 0.0, "max": 2.0, "default": None},
    {"key": "bot.sampling.top_p", "type": "float", "label": "Top-p",
     "section": "Behaviour", "min": 0.0, "max": 1.0, "default": None},
    {"key": "bot.sampling.frequency_penalty", "type": "float", "label": "Repeats itself less",
     "section": "Behaviour", "min": -2.0, "max": 2.0, "default": None},
    {"key": "bot.sampling.presence_penalty", "type": "float", "label": "Brings up new things",
     "section": "Behaviour", "min": -2.0, "max": 2.0, "default": None},
    # Same again: a config written before the refusal section still shows these,
    # with the values the app is actually running on.
    {"key": "bot.refusal.enabled", "type": "bool", "label": "Catch refusals",
     "section": "Behaviour", "default": True},
    {"key": "bot.refusal.fallbacks", "type": "json", "label": "Send instead",
     "section": "Behaviour", "default": ["wtf", "??"]},
    {"key": "bot.refusal.extra_phrases", "type": "json", "label": "Extra refusal phrases",
     "section": "Behaviour", "default": []},
    {"key": "bot.refusal.replace_phrases", "type": "bool", "label": "Use only my phrases",
     "section": "Behaviour", "default": False},
    {"key": "bot.tts.tones", "type": "json", "label": "Delivery", "section": "Behaviour"},
    {"key": "bot.late_reply.enabled", "type": "bool", "label": "Late reply openers",
     "section": "Conversation", "requires_restart": True},
    {"key": "bot.late_reply.threshold", "type": "int", "label": "Late reply threshold (s)",
     "section": "Conversation", "min": 30, "requires_restart": True},
    {"key": "bot.stale_reply.enabled", "type": "bool", "label": "Abandon stale replies",
     "section": "Conversation", "requires_restart": True},
    # A count with no top: drawn as a tape to pull (Tape.svelte).
    {"key": "bot.stale_reply.max_messages", "type": "int", "label": "Stale after",
     "section": "Conversation", "min": 1},
    {"key": "bot.stale_reply.min_age", "type": "int", "label": "Only once older than",
     "section": "Conversation", "min": 0},
    {"key": "bot.cache.max_messages", "type": "int", "label": "Messages kept in memory",
     "section": "Discord", "min": 0},
    {"key": "bot.friend_requests.enabled", "type": "bool", "label": "Auto-accept friend requests",
     "section": "General", "requires_restart": True},
    {"key": "bot.friend_requests.accept_delay_min", "type": "int", "label": "Accept delay min (s)",
     "section": "General", "min": 30, "requires_restart": True},
    {"key": "bot.friend_requests.accept_delay_max", "type": "int", "label": "Accept delay max (s)",
     "section": "General", "min": 30, "requires_restart": True},
    {"key": "bot.nudge.enabled", "type": "bool", "label": "Nudge unanswered DMs",
     "section": "Conversation", "requires_restart": True},
    {"key": "bot.nudge.threshold_days", "type": "int", "label": "Nudge after (days)",
     "section": "Conversation", "min": 1, "requires_restart": True},
    {"key": "notifications.telegram_error_notifications", "type": "bool",
     "label": "Error alerts", "section": "Notifications"},
    # Sent by the Telegram controller too: the supervisor queues one when an
    # account stops or keeps restarting (supervisor._alert_crash).
    {"key": "notifications.telegram_crash_alerts", "type": "bool",
     "label": "Crash alerts", "section": "Notifications", "default": True},
    {"key": "notifications.telegram_quiet", "type": "bool",
     "label": "Silent alerts", "section": "Notifications", "default": False},
    {"key": "snapchat.enabled", "type": "bool", "label": "Snapchat",
     "section": "Services", "needs": "snapchat"},
    {"key": "discord.enabled", "type": "bool", "label": "Discord", "section": "Services"},
    # Servers' own waits. Empty is "the same as DMs", which is how a config
    # without this key behaves, so the row is there to be filled in rather than
    # missing until someone adds the key by hand.
    {"key": "bot.server_batch_wait_times", "type": "json", "label": "Server wait times",
     "section": "Behaviour", "default": []},
    {"key": "snapchat.poll_interval_ms", "type": "int", "label": "Look for messages every",
     "section": "Snapchat", "min": 2000, "requires_restart": True},
    {"key": "snapchat.max_recipients", "type": "int", "label": "Chats opened each look",
     "section": "Snapchat", "min": 1, "max": 50, "requires_restart": True},
    {"key": "snapchat.min_send_gap_ms", "type": "int", "label": "Gap between sends, at least",
     "section": "Snapchat", "min": 1000, "requires_restart": True},
    {"key": "snapchat.max_send_gap_ms", "type": "int", "label": "Gap between sends, at most",
     "section": "Snapchat", "min": 1000, "requires_restart": True},
    {"key": "snapchat.max_sends_per_hour", "type": "int", "label": "Sends an hour, at most",
     "section": "Snapchat", "min": 1, "max": 200, "requires_restart": True},
    {"key": "snapchat.auto_add_friends", "type": "bool", "label": "Accept friend requests",
     "section": "Snapchat", "requires_restart": True},
    {"key": "snapchat.headless", "type": "bool", "label": "Hide the browser window",
     "section": "Snapchat", "requires_restart": True},
]


def get_schema() -> list:
    return CONFIG_SCHEMA


def get_nested(cfg: dict, dotted: str):
    node = cfg
    for part in dotted.split("."):
        if not isinstance(node, dict) or part not in node:
            return None
        node = node[part]
    return node


def set_nested(cfg: dict, dotted: str, value) -> dict:
    parts = dotted.split(".")
    node = cfg
    for part in parts[:-1]:
        node = node.setdefault(part, {})
        if not isinstance(node, dict):
            raise ValueError(f"{dotted}: {part} is not a mapping")
    node[parts[-1]] = value
    return cfg
